/Object_Follower:
  ros__parameters:
    theta_precision: 0.1
    distance_precision: 0.1
    pl: 0.015
    pa: 0.003
    ia: 0.000005
    radius_threshold : 130
    sum_ae : 0
    abuffer : 2
    lbuffer : 1

  #object_follower_controller:
    #theta_precision: 0.1
    #distance_precision: 0.1
    #pl: 0.015
    #pa: 0.003
    #ia: 0.000005
    #radius_threshold : 130
    #sum_ae : 0
    #abuffer : 2
    #lbuffer : 1
    